apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kubernetes-router.fullname" . }}
  labels:
    {{- include "kubernetes-router.labels" . | nindent 4 }}
data:
  username: {{ default (randAlphaNum 10) .Values.api.username | b64enc | quote }}
  password: {{ default (randAlphaNum 10) .Values.api.password | b64enc | quote }}