apiVersion: v1
kind: Service
metadata:
  name: {{ include "kubernetes-router.fullname" . }}
  labels:
    {{- include "kubernetes-router.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8077
      protocol: TCP
      name: http
  selector:
    {{- include "kubernetes-router.selectorLabels" . | nindent 4 }}
