bases:
- ../../nginx-operator/config/crd

# unfortunately the openAPIV3Schema validation wont work with clusters < 1.16+
# to work abroad with many different clusters, we need to disable this temporally
patches:
- target:
    group: apiextensions.k8s.io
    version: v1beta1
    kind: CustomResourceDefinition
    name: .*
  patch: |-
    - op: remove
      path: /spec/validation
