tsuru:
  pool:
    name: "default"

replicaCount: 1
prometheus:
  version: v2.24.0
  image:
    repository: quay.io/prometheus/prometheus

service:
  type: ClusterIP
  annotations: {}

resources: {}

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: "tsuru-prometheus-pool"

podAnnotations: {}
volumeClaimTemplate:
  spec:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 50Gi
    storageClassName: standard

securityContext:
  fsGroup: 2000
  runAsGroup: 2000
  runAsNonRoot: true
  runAsUser: 1000


networkPolicy:
  enabled: true
  k8sAPIAddresses: []
  # - IPs of k8s-apiserver


ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  host: default.mypool.io
  path: '/'
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local
